export function SiteFooter() {
  return (
    <footer className="border-t bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 mt-8">
      <div className="flex h-12 w-full items-center justify-center px-4 md:px-6 lg:px-8">
        <div className="flex w-full items-center justify-center" style={{ maxWidth: '1400px' }}>
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} Utopia.php • Generated by{' '}
            <a 
              href="https://imagine.dev" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:text-primary/80 transition-colors"
            >
              Imagine.dev
            </a>
            {' '}• Hosted on{' '}
            <a 
              href="https://appwrite.io" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:text-primary/80 transition-colors"
            >
              Appwrite Sites
            </a>
          </p>
        </div>
      </div>
    </footer>
  )
}
