export function SiteFooter() {
  return (
    <footer className="border-t bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 mt-8 py-6">
      <div className="flex min-h-12 w-full items-center justify-center px-4 md:px-6 lg:px-8">
        <div
          className="flex w-full items-center justify-center"
          style={{ maxWidth: '1400px' }}
        >
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} Utopia.php • Generated by{' '}
            <a
              href="https://imagine.dev"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:text-primary/80 transition-colors"
            >
              Imagine.dev
            </a>{' '}
            • Hosted on{' '}
            <a
              href="https://appwrite.io"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:text-primary/80 transition-colors"
            >
              Appwrite Sites
            </a>
          </p>
        </div>
      </div>
      <div className="flex justify-center items-center mt-2 gap-2">
        <span className="text-sm text-muted-foreground">Backed by</span>
        <a
          href="https://appwrite.io"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img
            src="https://appwrite.io/images/logos/appwrite.svg"
            alt="Appwrite"
            className="h-4 w-auto hidden dark:block"
          />
          <img
            src="https://appwrite.io/images/logos/appwrite-light.svg"
            alt="Appwrite"
            className="h-4 w-auto dark:hidden"
          />
        </a>
      </div>
    </footer>
  )
}
