/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicExampleCompsRouteImport } from './routes/_public/example-comps'
import { Route as PublicContributingRouteImport } from './routes/_public/contributing'
import { Route as PublicComparisonRouteImport } from './routes/_public/comparison'
import { Route as PublicChangelogRouteImport } from './routes/_public/changelog'
import { Route as PublicBlogRouteImport } from './routes/_public/blog'
import { Route as ProtectedExampleProtectedRouteRouteImport } from './routes/_protected/example-protected-route'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as PublicLibraryLibraryNameRouteImport } from './routes/_public/library.$libraryName'
import { Route as PublicLibraryLibraryNameConceptConceptPathRouteImport } from './routes/_public/library.$libraryName.concept.$conceptPath'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicExampleCompsRoute = PublicExampleCompsRouteImport.update({
  id: '/example-comps',
  path: '/example-comps',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContributingRoute = PublicContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicComparisonRoute = PublicComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedExampleProtectedRouteRoute =
  ProtectedExampleProtectedRouteRouteImport.update({
    id: '/example-protected-route',
    path: '/example-protected-route',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLibraryLibraryNameRoute =
  PublicLibraryLibraryNameRouteImport.update({
    id: '/library/$libraryName',
    path: '/library/$libraryName',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicLibraryLibraryNameConceptConceptPathRoute =
  PublicLibraryLibraryNameConceptConceptPathRouteImport.update({
    id: '/concept/$conceptPath',
    path: '/concept/$conceptPath',
    getParentRoute: () => PublicLibraryLibraryNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/blog': typeof PublicBlogRoute
  '/changelog': typeof PublicChangelogRoute
  '/comparison': typeof PublicComparisonRoute
  '/contributing': typeof PublicContributingRoute
  '/example-comps': typeof PublicExampleCompsRoute
  '/': typeof PublicIndexRoute
  '/library/$libraryName': typeof PublicLibraryLibraryNameRouteWithChildren
  '/library/$libraryName/concept/$conceptPath': typeof PublicLibraryLibraryNameConceptConceptPathRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/blog': typeof PublicBlogRoute
  '/changelog': typeof PublicChangelogRoute
  '/comparison': typeof PublicComparisonRoute
  '/contributing': typeof PublicContributingRoute
  '/example-comps': typeof PublicExampleCompsRoute
  '/': typeof PublicIndexRoute
  '/library/$libraryName': typeof PublicLibraryLibraryNameRouteWithChildren
  '/library/$libraryName/concept/$conceptPath': typeof PublicLibraryLibraryNameConceptConceptPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_api/hello': typeof ApiHelloRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/_public/blog': typeof PublicBlogRoute
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/comparison': typeof PublicComparisonRoute
  '/_public/contributing': typeof PublicContributingRoute
  '/_public/example-comps': typeof PublicExampleCompsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/library/$libraryName': typeof PublicLibraryLibraryNameRouteWithChildren
  '/_public/library/$libraryName/concept/$conceptPath': typeof PublicLibraryLibraryNameConceptConceptPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/example-protected-route'
    | '/blog'
    | '/changelog'
    | '/comparison'
    | '/contributing'
    | '/example-comps'
    | '/'
    | '/library/$libraryName'
    | '/library/$libraryName/concept/$conceptPath'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/example-protected-route'
    | '/blog'
    | '/changelog'
    | '/comparison'
    | '/contributing'
    | '/example-comps'
    | '/'
    | '/library/$libraryName'
    | '/library/$libraryName/concept/$conceptPath'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_api/hello'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_protected/example-protected-route'
    | '/_public/blog'
    | '/_public/changelog'
    | '/_public/comparison'
    | '/_public/contributing'
    | '/_public/example-comps'
    | '/_public/'
    | '/_public/library/$libraryName'
    | '/_public/library/$libraryName/concept/$conceptPath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/example-comps': {
      id: '/_public/example-comps'
      path: '/example-comps'
      fullPath: '/example-comps'
      preLoaderRoute: typeof PublicExampleCompsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contributing': {
      id: '/_public/contributing'
      path: '/contributing'
      fullPath: '/contributing'
      preLoaderRoute: typeof PublicContributingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/comparison': {
      id: '/_public/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof PublicComparisonRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/example-protected-route': {
      id: '/_protected/example-protected-route'
      path: '/example-protected-route'
      fullPath: '/example-protected-route'
      preLoaderRoute: typeof ProtectedExampleProtectedRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/library/$libraryName': {
      id: '/_public/library/$libraryName'
      path: '/library/$libraryName'
      fullPath: '/library/$libraryName'
      preLoaderRoute: typeof PublicLibraryLibraryNameRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/library/$libraryName/concept/$conceptPath': {
      id: '/_public/library/$libraryName/concept/$conceptPath'
      path: '/concept/$conceptPath'
      fullPath: '/library/$libraryName/concept/$conceptPath'
      preLoaderRoute: typeof PublicLibraryLibraryNameConceptConceptPathRouteImport
      parentRoute: typeof PublicLibraryLibraryNameRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedExampleProtectedRouteRoute: typeof ProtectedExampleProtectedRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedExampleProtectedRouteRoute: ProtectedExampleProtectedRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicLibraryLibraryNameRouteChildren {
  PublicLibraryLibraryNameConceptConceptPathRoute: typeof PublicLibraryLibraryNameConceptConceptPathRoute
}

const PublicLibraryLibraryNameRouteChildren: PublicLibraryLibraryNameRouteChildren =
  {
    PublicLibraryLibraryNameConceptConceptPathRoute:
      PublicLibraryLibraryNameConceptConceptPathRoute,
  }

const PublicLibraryLibraryNameRouteWithChildren =
  PublicLibraryLibraryNameRoute._addFileChildren(
    PublicLibraryLibraryNameRouteChildren,
  )

interface PublicRouteChildren {
  PublicBlogRoute: typeof PublicBlogRoute
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicComparisonRoute: typeof PublicComparisonRoute
  PublicContributingRoute: typeof PublicContributingRoute
  PublicExampleCompsRoute: typeof PublicExampleCompsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicLibraryLibraryNameRoute: typeof PublicLibraryLibraryNameRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBlogRoute: PublicBlogRoute,
  PublicChangelogRoute: PublicChangelogRoute,
  PublicComparisonRoute: PublicComparisonRoute,
  PublicContributingRoute: PublicContributingRoute,
  PublicExampleCompsRoute: PublicExampleCompsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicLibraryLibraryNameRoute: PublicLibraryLibraryNameRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
